
server:
  port: 8080

spring:


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/critical_skills_works
    username: root
    password: 1234



  mail:
    # 发送者邮箱
    username: 2859111272@qq.com
    #申请到的授权码
    password: yulhhydkrnwydejb
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 端口号465或587
    port: 465
    protocol: smtps
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
          debug: true
          ssl: true
  data:
    redis:
      host: localhost
      port: 6379
      password:


  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB



mybatis:

  configuration-properties:
    helperDialect: mysql
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true
  mapper-locations: mybatis/mapper/*.xml

  configuration:
    map-underscore-to-camel-case: true

